"""create items table

Revision ID: 719ca81ba45b
Revises: 
Create Date: 2025-05-01 07:27:52.099114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '719ca81ba45b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
